version: "3"

services:
  line:
    build: .
    container_name: line_fastapi_container
    environment:
      MONGODB_HOST: "line_mongodb_container"
      MONGODB_DATABASE: "conversationdb"
      MONGODB_COLLECTION: "learning_companion"
      LINE_ACCESS_TOKEN: "3Vse/GaAdqdZ2gDP8QykIEn0aQMnxiCI8hpR+JZK4tUA/d11KWjcl5MgeurvAklyBKft8Bl2Vh0h1k/tsniAmyrKZVGekwCZGaxTvPqnIFA5Hk8IdM3HpSxKWfM0ylAcMfDH9rxbJttDdDnKF1ccGAdB04t89/1O/w1cDnyilFU="
      LINE_CHANNEL_SECRET: "e53cbac7c9c923fd3c18fc49ba43db3a"
      GPT_API_URL: "https://model.hsueh.tw/callapi/chatGPT"
      DATABASE_URL: "postgresql://postgres:1234@140.115.126.110:5432/postgres"
      RAG_ENDPOINT: "http://ml.hsueh.tw:8000"
      
    volumes:
      - ./main.py:/app/main.py
    ports:
      - "25000:25000"
    depends_on:
      - mongodb      
    networks:
      - line_agent_network

  mongodb:
    image: mongo
    container_name: line_mongodb_container
    ports:
      - "27018:27017"
    networks:
      - line_agent_network

volumes:
  postgres_data:

networks:
  line_agent_network:
