version: "3"

services:
  line:
    build: .
    container_name: line_fastapi_container
    environment:
      MONGODB_HOST: "line_mongodb_container"
      MONGODB_DATABASE: "conversationdb"
      MONGODB_COLLECTION: "learning_companion"
      LINE_ACCESS_TOKEN: "Y5inqLI3ZsckR5j1L7JdHAG4zpC+6W5yLjsUMRC+Y3ZzPs+pw1kqpPjXZsw+mbBXK1EKINUTsAHibFVebKJzZxkbac6xdhZ6MHTfXh5wlyN7lpn5BtEESPDn7gQOVEWuJEkd10/mydXXIU8KPyATuQdB04t89/1O/w1cDnyilFU="
      LINE_CHANNEL_SECRET: "95f8ea74a89132626f6756564aa977ec"
      GPT_API_URL: "https://model.hsueh.tw/callapi/chatGPT"
      DATABASE_URL: "postgresql://postgres:1234@140.115.126.110:5432/postgres"
      #DATABASE_URL: postgresql://postgres:1234@localhost:5432/aitest
      
    volumes:
      - ./main.py:/app/main.py
    ports:
      - "25000:25000"
    depends_on:
      - mongodb      
    networks:
      - line_agent_network

  mongodb:
    image: mongo
    container_name: line_mongodb_container
    ports:
      - "27018:27017"
    networks:
      - line_agent_network

volumes:
  postgres_data:

networks:
  line_agent_network:
